### ISSUE TITLE
Can't bundle imported types to the entry file

### ISSUE THREAD

**Issue by erguotou520** [ryoppippi/bun-plugin-isolated-decl#11]
For example
```ts
// index.ts
export * from './a'
```
```ts
// a.ts
export type A = number
```
The build script is
```ts
await Bun.build({
  entrypoints: ['./src/index.ts'],
  outdir: './dist',
  format: 'esm',
  target: 'browser',
  plugins: [isolatedDecl()]
})
```
This plugin just generate `export * from './a'` with no `type A` definition bundled.

**Comment by ryoppippi** [comment]
You should also add `a.ts` to entrypoints.
in current implementation or oxs bug, types are not bundles inline

**Comment by cybercoder-naj** [comment]
> You should also add `a.ts` to entrypoints. in current implementation or oxs bug, types are not bundles inline

However this is not the correct way to go around this issue. As per `tsc`, you should return all files with exported types.

**Comment by erguotou520** [comment]
> You should also add `a.ts` to entrypoints. in current implementation or oxs bug, types are not bundles inline

This is not the correct way. It should be auto-collected.
