### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by RobinTail** [ryoppippi/bun-plugin-isolated-decl#12]
When I follow the installation instructions from the Readme file, I get the following error:

```
error: Cannot find package "oxc-transform" from ".../node_modules/bun-plugin-isolated-decl/index.ts"
```

It seems that `oxc-transform` is a peer dependency that has to be installed manually. After doing so it works.
But it's not mentioned as peer in Readme and in your `package.json` file.

**Comment by ryoppippi** [comment]
@RobinTail 
Thank you for reporting this.
Could you create a PR to fix this?

**Comment by RobinTail** [comment]
Done, @ryoppippi : 
https://github.com/ryoppippi/bun-plugin-isolated-decl/pull/13
