### ISSUE TITLE
Preserve JSDoc

### ISSUE THREAD

**Issue by RobinTail** [ryoppippi/bun-plugin-isolated-decl#14]
Is there an option or a way to preserve JSDoc comments in the generated DTS file, @ryoppippi ?

**Comment by ryoppippi** [comment]
@RobinTail 
For now, there is not way to do it.
At least, oxc does not support it maybe

**Comment by ryoppippi** [comment]
I'll try using swc, which may support it, but idk

**Comment by RobinTail** [comment]
Probably related to this: https://github.com/oxc-project/oxc/issues/3906

**Comment by ryoppippi** [comment]
Yeah he is creating a kind of same thing

**Comment by ryoppippi** [comment]
@RobinTail 
FYI, I have started to use `tsdown`(`rolldown` based), and they are great(maybe better than Bun.build).
(However, rolldown based on oxc, so JSDocs are gone too...)

**Comment by ryoppippi** [comment]
Ok, I'll close this because this is oxc's isssue!
